# Minos Panel Configuration

server:
  addr: ':28473'
  gateway: /gateway
  tls:
    certificate: /usr/local/minos/data/cert/server.crt
    key: /usr/local/minos/data/cert/server.key
    enhance: true

admin:
  addr: ':31742'
  password: EenyMeenyMinosMoe
  observer: 11111
  builder: "12345x"
  discard: true
  security:
    tornet: false
    phrase: See Copyright Notice in the LICENSE file
    referer: false
    limitrate: 10
    pwdguard: [10, 1800]
    logfile: /usr/local/minos/data/login.dat
  tls:
    certificate: /usr/local/minos/data/cert/server.crt
    key: /usr/local/minos/data/cert/server.key

wallets:
  btc: 'https://www.blockchain.com/explorer/addresses/btc/'
  eth: 'https://debank.com/profile/'
  ronin: 'https://explorer.roninchain.com/address/'
  sol: 'https://solscan.io/account/'
  tron: 'https://tronscan.org/#/address/'
  kardia: 'https://explorer.kardiachain.io/address/'

duphidden: true
nonascii: true
filevirtprefix: repo

knownlist: /usr/local/minos/data/private/known_list.yaml
database: /usr/local/minos/data/db/index
container: /usr/local/minos/data/db
exportdir: /usr/local/minos/exports
tempdir: /usr/local/minos/data/temp
rootfs: /usr/local/minos/data/download
indexeddb: /usr/local/minos/data/idb
pluginfs: /usr/local/minos/data/plugins
plugindata: /usr/local/minos/data/userdata
filesyncdir: /usr/local/minos/data/filesync
geo2ip: /usr/local/minos/data/private/GeoLite2-City.mmdb
pubsflist: /usr/local/minos/data/private/public_suffix_list.dat
framework: /usr/local/minos/data/framework/admin.zip
blockips: /usr/local/minos/data/private/blackips.dat
savedopt: /usr/local/minos/data/private/options.dat
cachesdb: /usr/local/minos/data/private/global.db
treventdb: /usr/local/minos/data/private/event.db
userdb: /usr/local/minos/data/private/users.db
userdir: /usr/local/minos/data/users
restart: /usr/local/minos/data/private/restart.sh
traffickerdb: /usr/local/minos/data/private/trafficker.db
feature: /usr/local/minos/data/private/feature.db
tessdata: /usr/local/minos/data/share/tessdata
torordatadir: /usr/local/minos/data/share/tordata
torrc: /usr/local/minos/data/share/torrc
stubtemplate: /usr/local/minos/data/framework/dist.zip
disguise: /usr/local/minos/data/framework/wwwroot.zip
fwcmd: /usr/local/minos/data/private/firewall.yaml
persistdata: /usr/local/minos/data/private/pt.bin
tskexpire: 24h
disbanner: true
exptags: true
wwwroot: /

openapi:
  token: 123321

clusterbase: /usr/local/minos/bin
manifest: /usr/local/minos/data/private/dist.sign

telegram:
  bot_token: ""
  channel_id: ""
